name: 'Deploy web app'

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    defaults:
      run:
        working-directory: ./
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Publish
      run: dotnet publish '' -c Release -o '_api'
      
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: noneed
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './_api'
